[package]
name = "indexer"
version = "1.2.3"
authors = ["Gabriel Farrell"]
edition = "2021"


[dependencies]
quick-xml = { version = "0.28.2", features = ["serialize"] }
serde = "1.0.160"
serde_derive = "1.0.160"
clap = { version = "4.2.5", features = ["derive"] }
rusqlite = "0.29.0"
