[workspace]

members = [
  "process_input"
]

[workspace.package]
version = "1.2.3"
authors = ["Gabriel Farrell"]
description = "A short description of my package"
documentation = "https://example.com/bar"
