[package]
name = "process_json_input"
version = "0.1.0"
edition = "2021"

[dependencies]
#quick-xml = "0.28.2"
quick-xml = { version = "0.28.2", features = ["serialize"] }
serde = "1.0.160"
serde-xml-rs = "0.6.0"
serde_derive = "1.0.160"
rusqlite = { version = "0.29.0", features = ["bundled"] }
